apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: 3111
        resources: {}
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
        livenessProbe:
            httpGet:
                path: /healthz
                port: 3111
            initialDelaySeconds: 10
            periodSeconds: 5
        readinessProbe:
            httpGet:
                path: /healthz
                port: 3111
            initialDelaySeconds: 10
            periodSeconds: 5