apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: 
      port: 4111
      targetPort: 3111
  type: ClusterIP