apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  ports:
    - protocol: 
      port: 4111
      targetPort: 3111
  type: ClusterIP