namespace:
  name: production

service:
  port: 7111
  targetPort: 3111

app:
  name: techtrends
  port: 3111
  reqMemory: "128Mi"
  reqCpu: "350m"
  limMemory: "256Mi"
  limCpu: "500m"
  livenessProbe:
    path: /healthz
    port: 3111
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    path: /healthz
    port: 3111
    initialDelaySeconds: 10
    periodSeconds: 5
replicaCount: 5

image:
  repository: nat389/techtrends
  tag: latest
  pullPolicy: Always