namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111

app:
  name: techtrends
  port: 3111
  reqMemory: "64Mi"
  reqCpu: "250m"
  limMemory: "128Mi"
  limCpu: "500m"
  livenessProbe:
    path: /healthz
    port: 3111
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    path: /healthz
    port: 3111
    initialDelaySeconds: 10
    periodSeconds: 5
replicaCount: 1

image:
  repository: nat389/techtrends
  tag: latest
  pullPolicy: IfNotPresent